# 格式: username:password:home_dir:permission:enabled
# permission: none, read, write, admin

admin:admin123:/var/ftpd/root:admin:1
user:password123:/var/ftpd/root/home:write:1
anonymous::/var/ftpd/root/pub:read:1
